version: '3.8'
name: opencodequest-leaderboard

networks:
  monitoring: {}

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  grafana:
    image: docker.io/grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
    - GF_LOG_LEVEL=debug
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - monitoring

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:z
      - ./prometheus/recording_rules.yaml:/etc/prometheus/recording_rules.yaml:z
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - monitoring
