{
 "title": "Leaderboard explanation",
 "time": { "from": "2024-10-11T13:03:20.000Z", "to": "2024-10-11T13:06:20.000Z" },
 "panels": [
  {
   "title": "opencodequest_leaderboard_hero:prod => Exercise completion state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_hero:prod{user=\"catwoman\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_villain:prod => Exercise completion state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_villain:prod{user=\"catwoman\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_fight:prod => Exercise completion state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_fight:prod{user=\"catwoman\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_hero_lifetime_bonus:prod => Time bonus, carried forward",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_hero_onetime_bonus:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_villain_lifetime_bonus:prod => Time bonus, carried forward",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_villain_onetime_bonus:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_fight_lifetime_bonus:prod => Time bonus, carried forward",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_fight_onetime_bonus:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum_over_time(opencodequest_leaderboard_hero:prod[1h]) => Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_hero:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum_over_time(opencodequest_leaderboard_villain:prod[1h]) => Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_villain:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sum_over_time(opencodequest_leaderboard_fight:prod[1h]) => Accelerator",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_fight:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Points earned over time",
   "type": "timeseries",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_hero_lifetime_bonus:prod{user=\"catwoman\"}\n+ sum_over_time(opencodequest_leaderboard_hero:prod{user=\"catwoman\"}[1h])\n+ opencodequest_leaderboard_villain_lifetime_bonus:prod{user=\"catwoman\"}\n+ sum_over_time(opencodequest_leaderboard_villain:prod{user=\"catwoman\"}[1h])\n+ opencodequest_leaderboard_fight_lifetime_bonus:prod{user=\"catwoman\"}\n+ sum_over_time(opencodequest_leaderboard_fight:prod{user=\"catwoman\"}[1h])\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}