{
 "title": "Time Bonus (carry forward)",
 "time": { "from": "2024-10-11T13:03:20.000Z", "to": "2024-10-11T13:06:20.000Z" },
 "panels": [
  {
   "title": "opencodequest_leaderboard_hero:prod => Exercise completion state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_hero:prod{user=\"catwoman\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_hero_onetime_bonus:prod => Time bonus for the user",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "(increase(opencodequest_leaderboard_hero:prod[10s]) >= bool 0.5)\n*\n(\n  55\n  +\n  sum(\n      (\n        1728651786 + 55\n        -\n        timestamp(\n          label_replace(up{instance=\"localhost:9090\"}, \"user\", \"catwoman\", \"\",\"\")\n        )\n      ) / 5\n  ) by (user)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_hero_lifetime_bonus:prod => Time bonus for the user (carry forward)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum_over_time(opencodequest_leaderboard_hero_onetime_bonus:prod{user=\"catwoman\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}