{
 "title": "Time Bonus",
 "time": { "from": "2024-10-11T13:03:20.000Z", "to": "2024-10-11T13:06:20.000Z" },
 "panels": [
  {
   "title": "opencodequest_leaderboard_hero:prod => Exercise completion state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "opencodequest_leaderboard_hero:prod{user=\"catwoman\"}",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "increase(opencodequest_leaderboard_hero:prod[10s]) >= bool 0.5 => Change of exercise completion stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "increase(opencodequest_leaderboard_hero:prod{user=\"catwoman\"}[10s]) >= bool 0.5",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "55 + sum(($TS - timestamp(...) / 5) by (user) => Evolution of the time bonus over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "55\n+\nsum(\n    (\n      1728651786 + 55\n      -\n      timestamp(\n        label_replace(up{instance=\"localhost:9090\"}, \"user\", \"catwoman\", \"\",\"\")\n      )\n    ) / 5\n  ) by (user)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "opencodequest_leaderboard_hero_onetime_bonus:prod => Time bonus for the user",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "(increase(opencodequest_leaderboard_hero:prod[10s]) >= bool 0.5)\n*\n(\n  55\n  +\n  sum(\n      (\n        1728651786 + 55\n        -\n        timestamp(\n          label_replace(up{instance=\"localhost:9090\"}, \"user\", \"catwoman\", \"\",\"\")\n        )\n      ) / 5\n  ) by (user)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}